package test4giis.tdrules.tdg.st.test.market;

import org.junit.Test;

import giis.tdrules.store.loader.DataLoader;
import giis.tdrules.store.loader.gen.IAttrGen;

/**
 * Carts Functionality Tests.
 * - Use the live SUT where the uids of each generated object are generated by the backend.
 * - Use the dictionary
 * - Include Users, Carts and Orders
 */
public class TestMarketFuncCarts extends BaseMarket {
	
	@Override
	protected boolean isLiveBackend() {
		return true;
	}
	
	@Test
	public void testDictUserDTOResByName() {
		String query = queryUserByName;
		IAttrGen dict=getDictionaryAttrGen();
		DataLoader dg = getLiveDataLoader().setAttrGen(dict);
		generateAndLoad(dg, query, dict);
		assertData("func-UsersByName.txt", dg);
	}

	@Test
	public void testDictCartDTOByUser() {
		String query = queryCartByUser;
		IAttrGen dict=getDictionaryAttrGen();
		DataLoader dg = getLiveDataLoader().setAttrGen(dict);
		generateAndLoad(dg, query, dict);
		assertData("func-CartsByUser.txt", dg);
	}
	
	@Test
	public void testDictCartDTOByUserProductQuantity() {
		String query = queryCartByUserProductQuantity;
		IAttrGen dict=getDictionaryAttrGen();
		DataLoader dg = getLiveDataLoader().setAttrGen(dict);
		generateAndLoad(dg, query, dict);
		assertData("func-CartsByUserProductQuantity.txt", dg);
	}

	@Test
	public void testDictCartDTOByUserChangeProductQuantity() {
		String query = queryCartByUserProductQuantity;
		// Cambio en la cardinalidad del producto 1
		String query2 = "tds CartDTO,CartItemDTORes,ProductDTORes where CartDTO.user='pepe@email.com' and CartItemDTORes.productId=1 and CartItemDTORes.quantity=3 and ProductDTORes.available=1";
		
		
		IAttrGen dict=getDictionaryAttrGen();
		DataLoader dg = getLiveDataLoader().setAttrGen(dict);
		//generateAndLoad(dg, query, dict);
		//generateAndLoad(dg, query2, dict);
		generateAndLoad(dg, new String[] {query, query2}, dict);
		assertData("func-CartsByUserProductQuantity.txt", dg);
	}
}
