name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Maven project
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: m2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Compile
        run: mvn --file pom.xml clean compile

      - name: Build
        run: mvn --file pom.xml install

      - name: Report coverage to Codacy
        shell: bash
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          if [ "$CODACY_PROJECT_TOKEN" != "" ] ; then
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r market-coverage/target/coverage-report/coverage-report.xml
          else
            echo "No CODACY_PROJECT_TOKEN provided for Codacy report"
          fi