package test4giis.tdrules.tdg.st.test.petstore;

import org.junit.Test;

import giis.tdrules.store.loader.DataLoader;

/** 
 * Test Data generation for APIs (TDG) for the Swagger Petstore as SUT:
 * Full integration of data generation with QAGrow and loading using a live SUT where the uids 
 * of each generated object are generated by the backend.
 */
public class TestPetstoreQagrowLiveBackId extends TestPetstoreDatagenLiveBackId {

	@Test
	public void testPetByCategoryAndStatus() {
		DataLoader dg = getDataLoader();
		generateAndLoad(dg, TestPetstoreDatagenLocal.queryPetByCategoryAndStatus);
		assertData("qagrow-livebackid-pet-by-category-status.txt", dg);
	}

}
